version: '2'

services:
  cqhttp:
    image: nanahira/go-cqhttp:latest
    container_name: koishi-go-cqhttp
    volumes:
      - ./cqhttp:/data
    environment:
      UIN: myQQID  # change it
      PASS: myQQPassword  # change it
      HTTP_POST: http://koishi:8080

  mysql:
    image: mariadb:10
    container_name: koishi-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: myPassword  # change it
      MYSQL_DATABASE: koishi
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  koishi:
    image: koishijs/koishi:latest
    container_name: koishi
    volumes:
      - ./koishi:/config
    environment:
      TYPE: http
      SERVER: http://cqhttp:5700
