FROM node:lts-alpine
LABEL maintainer="NN708"

RUN apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont font-noto-cjk
RUN adduser -D koishi
USER koishi

WORKDIR /home/koishi
RUN yarn create koishi koishi-app -y && cd koishi-app && \
    sed -i 's/host: .*/host: 0.0.0.0/g' koishi.yml && \
    yarn install

WORKDIR /home/koishi/koishi-app

ENTRYPOINT [ "yarn", "start" ]
