export const DUPLICATE_COMMAND = 'duplicate command names'
export const DUPLICATE_OPTION = 'duplicate option names'
export const EXPECT_COMMAND_NAME = 'expect a command name'
export const INVALID_CONTEXT = 'invalid context path'
export const INVALID_IDENTIFIER = 'invalid context identifier'
export const INVALID_SUBCOMMAND = 'invalid subcommand'
export const ISOLATED_NEXT = 'isolated next function'
