name: Milestone Issue Backlog

on:
  issues:
    types:
      - "milestoned"
      - "demilestoned"

jobs:
  backlog:
    name: Backlog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Prepare packages
        run: npm i @actions/github
      - name: Backlog
        env:
          PAT: ${{ secrets.BACKLOG_PAT }}
        run: node ./.github/workflows/backlog.js
